name: Backend CI/CD

# Trigger workflow on push to main branch, but only for back-end changes
on:
  push:
    branches:
      - main
    paths:
      - 'back-end/**'

jobs:
  deploy-backend:
    name: Deploy Backend to Cloud Run
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud credentials
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set Google Cloud project
      - name: Set Google Cloud Project
        run: gcloud config set project email-management-449416

      # Step 4: Configure Docker to use GCP Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t asia-south1-docker.pkg.dev/email-management-449416/email-backend-repo/email-backend:latest .

      # Step 6: Push Docker image to Artifact Registry
      - name: Push Docker image
        run: |
          docker push asia-south1-docker.pkg.dev/email-management-449416/email-backend-repo/email-backend:latest

      # Step 7: Deploy Docker image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy email-backend \
            --project=email-management-449416 \
            --image=asia-south1-docker.pkg.dev/email-management-449416/email-backend-repo/email-backend:latest \
            --platform=managed \
            --region=asia-south1 \
            --allow-unauthenticated \
            --service-account=767837784755-compute@developer.gserviceaccount.com \
            --port=3000 \
            --set-secrets BASE_URL=BASE_URL:latest \
            --set-secrets GOOGLE_REDIRECT_URI=GOOGLE_REDIRECT_URI:latest \
            --set-secrets JWT_SECRET=JWT_SECRET:latest \
            --set-secrets JWT_REFRESH_SECRET=JWT_REFRESH_SECRET:latest \
            --set-secrets EMAIL_USER=EMAIL_USER:latest \
            --set-secrets EMAIL_PASS=EMAIL_PASS:latest \
            --set-secrets CLIENT_ID=CLIENT_ID:latest \
            --set-secrets CLIENT_SECRET=CLIENT_SECRET:latest \
            --set-secrets REFRESH_TOKEN=REFRESH_TOKEN:latest \
            --set-secrets GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest \
            --set-secrets GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest
